// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG1r0L9zueB5n8ICk43nyion29H8ly46g',
    appId: '1:709081647579:web:2e4ae96ba0cb8fcd21fffe',
    messagingSenderId: '709081647579',
    projectId: 'grocery-list-5dcac',
    authDomain: 'grocery-list-5dcac.firebaseapp.com',
    storageBucket: 'grocery-list-5dcac.firebasestorage.app',
    measurementId: 'G-Z7XXE0WE0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGS7K-YzT7CSRki9oe7lsJB_nz6jl2vKc',
    appId: '1:709081647579:android:4747de6a7430520221fffe',
    messagingSenderId: '709081647579',
    projectId: 'grocery-list-5dcac',
    storageBucket: 'grocery-list-5dcac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Y29m7UkYJBNZCtqIJcPsiiZOaUi7Py8',
    appId: '1:709081647579:ios:96b6fcad890ccdf321fffe',
    messagingSenderId: '709081647579',
    projectId: 'grocery-list-5dcac',
    storageBucket: 'grocery-list-5dcac.firebasestorage.app',
    iosBundleId: 'com.example.groceryListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Y29m7UkYJBNZCtqIJcPsiiZOaUi7Py8',
    appId: '1:709081647579:ios:96b6fcad890ccdf321fffe',
    messagingSenderId: '709081647579',
    projectId: 'grocery-list-5dcac',
    storageBucket: 'grocery-list-5dcac.firebasestorage.app',
    iosBundleId: 'com.example.groceryListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG1r0L9zueB5n8ICk43nyion29H8ly46g',
    appId: '1:709081647579:web:d17199ffa68fdfff21fffe',
    messagingSenderId: '709081647579',
    projectId: 'grocery-list-5dcac',
    authDomain: 'grocery-list-5dcac.firebaseapp.com',
    storageBucket: 'grocery-list-5dcac.firebasestorage.app',
    measurementId: 'G-5HTB2BEZ14',
  );
}
